"""
myco/tools/registry.py
Plugin-style tool registry.
Built-in tools + runtime registration of dynamically-generated tools.
"""
from __future__ import annotations
import asyncio, logging
from typing import Callable, Any

log = logging.getLogger("myco.tools")


class ToolRegistry:
    """
    Manages all of Myco's callable tools.
    Tools can be registered at startup (config) or at runtime (self-improvement).
    """

    def __init__(self, enabled: list[str] | None = None):
        self._tools: dict[str, dict] = {}
        self._register_builtins()
        # disable tools not in the enabled list (if provided)
        if enabled:
            self._tools = {k: v for k, v in self._tools.items() if k in enabled}

    def register(self, name: str, fn: Callable, description: str = "", safe: bool = True):
        self._tools[name] = {"fn": fn, "description": description, "safe": safe, "dynamic": False}

    def register_dynamic(self, name: str, fn: Callable, description: str = ""):
        """Register a tool generated by the self-improvement engine."""
        self._tools[name] = {"fn": fn, "description": description, "safe": True, "dynamic": True}
        log.info(f"Dynamic tool registered: {name}")

    async def execute(self, name: str, args: dict) -> Any:
        if name not in self._tools:
            return f"Unknown tool: {name}. Available: {self.list_available()}"
        tool = self._tools[name]
        try:
            result = tool["fn"](**args)
            if asyncio.iscoroutine(result):
                result = await result
            return result
        except Exception as e:
            log.warning(f"Tool {name} failed: {e}")
            return f"Tool error: {e}"

    def list_available(self) -> list[str]:
        return list(self._tools.keys())

    def describe(self) -> str:
        lines = []
        for name, t in self._tools.items():
            tag = " [dynamic]" if t.get("dynamic") else ""
            lines.append(f"  {name}{tag}: {t['description']}")
        return "\n".join(lines)

    # ── built-in tools ────────────────────────────────────────────────────────

    def _register_builtins(self):
        self.register("calculator",   _calculator,   "Evaluate a math expression safely")
        self.register("current_time", _current_time, "Return current UTC time")
        self.register("web_search",   _web_search,   "Search the web for information")
        self.register("read_file",    _read_file,    "Read a file from data/ or config/")
        self.register("write_memory", _write_memory, "Store a key-value note in working memory")
        self.register("read_memory",  _read_memory,  "Read a note from working memory by key")
        self.register("list_memory",  _list_memory,  "List all keys in working memory")
        self.register("run_python",   _run_python,   "Execute a safe Python snippet", safe=False)


# ── built-in tool implementations ────────────────────────────────────────────

def _calculator(expression: str) -> str:
    import ast, operator
    ops = {
        ast.Add: operator.add, ast.Sub: operator.sub,
        ast.Mult: operator.mul, ast.Div: operator.truediv,
        ast.Pow: operator.pow, ast.USub: operator.neg,
        ast.UAdd: operator.pos, ast.Mod: operator.mod
    }
    def _eval(node):
        if isinstance(node, ast.Constant):
            return node.value
        if isinstance(node, ast.BinOp):
            return ops[type(node.op)](_eval(node.left), _eval(node.right))
        if isinstance(node, ast.UnaryOp):
            return ops[type(node.op)](_eval(node.operand))
        raise ValueError(f"Unsafe expression: {ast.dump(node)}")
    try:
        tree = ast.parse(expression, mode='eval')
        result = _eval(tree.body)
        return str(round(result, 10))
    except Exception as e:
        return f"Calc error: {e}"

def _current_time() -> str:
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

async def _web_search(query: str) -> str:
    """DuckDuckGo instant answer (no API key needed)."""
    try:
        import httpx
        async with httpx.AsyncClient(timeout=10) as client:
            r = await client.get(
                "https://api.duckduckgo.com/",
                params={"q": query, "format": "json", "no_html": "1"}
            )
            data = r.json()
            abstract = data.get("AbstractText", "")
            if abstract:
                return abstract[:500]
            related = data.get("RelatedTopics", [])
            if related:
                return related[0].get("Text", "No results")[:300]
            return "No results found."
    except Exception as e:
        return f"Search failed: {e}"

def _read_file(path: str) -> str:
    from pathlib import Path
    try:
        p = Path(path).resolve()
        # Path traversal guard: only allow reads inside current working directory
        cwd = Path.cwd().resolve()
        allowed_roots = [cwd / "data", cwd / "config"]
        if not any(str(p).startswith(str(root)) for root in allowed_roots):
            return f"Access denied: '{path}' is outside allowed directories (data/, config/)"
        if not p.exists():
            return f"File not found: {path}"
        if p.stat().st_size > 1_000_000:  # 1 MB limit
            return f"File too large (max 1 MB)"
        return p.read_text(encoding="utf-8")[:4000]
    except Exception as e:
        return f"File read error: {e}"

_WORKING_MEMORY: dict[str, str] = {}

def _write_memory(key: str, value: str) -> str:
    key = key[:100].strip()
    if not key:
        return "Error: key cannot be empty"
    _WORKING_MEMORY[key] = str(value)[:2000]
    return f"Stored '{key}' in working memory."

def _read_memory(key: str) -> str:
    key = key.strip()
    if key not in _WORKING_MEMORY:
        available = list(_WORKING_MEMORY.keys())[:10]
        return f"Key '{key}' not found. Available keys: {available}"
    return _WORKING_MEMORY[key]

def _list_memory() -> str:
    if not _WORKING_MEMORY:
        return "Working memory is empty."
    return "Keys in working memory: " + ", ".join(list(_WORKING_MEMORY.keys())[:50])

def _run_python(code: str) -> str:
    """Very limited sandbox: no imports, no file I/O, no network, no introspection."""
    import builtins
    # FIX: removed getattr, hasattr, vars, dir, type, repr, id, callable, iter, next
    # These enable class introspection chains like:
    #   ().__class__.__bases__[0].__subclasses__() → escape to arbitrary builtins
    safe_builtins = {
        k: getattr(builtins, k)
        for k in [
            "abs", "all", "any", "bin", "bool", "chr", "complex",
            "divmod", "enumerate", "filter", "float", "format",
            "frozenset", "hex", "int", "isinstance", "issubclass",
            "len", "list", "map", "max", "min",
            "oct", "ord", "pow", "range", "reversed",
            "round", "set", "slice", "sorted", "str", "sum",
            "tuple", "zip", "dict",
            "True", "False", "None",
            "Exception", "ValueError", "TypeError",
        ]
        if hasattr(builtins, k)
    }
    output: list[str] = []
    def _print(*args, **kwargs):
        line = " ".join(str(a) for a in args)
        if sum(len(l) for l in output) < 4000:
            output.append(line)

    safe_builtins["print"] = _print
    try:
        exec(code, {"__builtins__": safe_builtins})
        return "\n".join(output) or "OK (no output)"
    except Exception as e:
        return f"Error: {e}"
